package com.gek.and.project4.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gek.and.project4.entity.Project;
import com.gek.and.project4.entity.Booking;

import com.gek.and.project4.dao.ProjectDao;
import com.gek.and.project4.dao.BookingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectDaoConfig;
    private final DaoConfig bookingDaoConfig;

    private final ProjectDao projectDao;
    private final BookingDao bookingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        bookingDaoConfig = daoConfigMap.get(BookingDao.class).clone();
        bookingDaoConfig.initIdentityScope(type);

        projectDao = new ProjectDao(projectDaoConfig, this);
        bookingDao = new BookingDao(bookingDaoConfig, this);

        registerDao(Project.class, projectDao);
        registerDao(Booking.class, bookingDao);
    }
    
    public void clear() {
        projectDaoConfig.getIdentityScope().clear();
        bookingDaoConfig.getIdentityScope().clear();
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public BookingDao getBookingDao() {
        return bookingDao;
    }

}
